packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  eslint: ^9.34.0
  next: ^15.5.2
  prettier: ^3.6.2
  tailwindcss: ^4.1.12
  typescript: ^5.9.2
  zod: ^4.0.17
  '@t3-oss/env-nextjs': ^0.13.8
  '@tanstack/react-query': ^5.80.7
  '@trpc/client': ^11.5.0
  '@trpc/next': ^11.5.0
  '@trpc/react-query': ^11.5.0
  '@trpc/server': ^11.5.0
catalogs:
  react19:
    react: 19.1.1
    react-dom: 19.1.1
    '@types/react': ^19.1.6
    '@types/react-dom': ^19.1.9
ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - bufferutil
  - prisma
  - utf-8-validate
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
