packages:
  - apps/*
  - packages/*
  - tooling/*
injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build
catalog:
  "@t3-oss/env-core": ^0.13.8
  "@types/node": ^24.3.3
  "@types/nodemailer": ^7.0.1
  date-fns: ^4.1.0
  date-fns-tz: ^3.2.0
  dotenv-cli: ^10.0.0
  drizzle-orm: ^0.44.5
  eslint: ^9.35.0
  next-auth: ^4.24.15
  nodemailer: ^7.0.7
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  redis: ^5.8.2
  typescript: ^5.9.2
  typescript-eslint: ^8.43.0
  zod: ^4.1.8
  "@t3-oss/env-nextjs": ^0.13.8
  "@tanstack/react-query": ^5.80.7
  "@trpc/client": ^11.5.1
  "@trpc/next": ^11.5.1
  "@trpc/react-query": ^11.5.1
  "@trpc/server": ^11.5.1
catalogs:
  react19:
    react: 19.2.8
    react-dom: 19.2.8
    "@types/react": ^19.2.18
    "@types/react-dom": ^19.2.4
overrides:
  react: catalog:react19
  react-dom: catalog:react19
peerDependencyRules:
  allowedVersions:
    "next-auth>@auth/core": 0.41.3
allowBuilds:
  "@prisma/client": false
  "@prisma/engines": false
  "@tailwindcss/oxide": true
  better-sqlite3: true
  bufferutil: false
  esbuild: true
  prisma: false
  sharp: true
  utf-8-validate: false
